on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main", "master"]

jobs:
  owasp_zap:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: |
        nohup npm start & # Inicia a aplicação em segundo plano
        sleep 20 # Aguarda a aplicação subir (ajuste conforme necessário)

    - name: Wait for application to be ready
      run: |
        for i in {1..10}; do
          curl -s http://localhost:3000 > /dev/null && break || sleep 5
        done

    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: "http://localhost:3000" # Substitua pela URL da sua aplicação, se necessário
        rules_file_name: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save OWASP ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: owasp-zap-report
        path: |
          report.html
          report.json
          report.md

    - name: Display HTML report
      run: cat report.html
