name: Docker Scout Analysis

on:
  push:
    branches:
      - main

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # Configurar Docker CLI
      - name: Configure Docker CLI
        run: |
          echo "${{ secrets.DOCKER_HUB_USERNAME }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Analisar a imagem com Docker Scout
      - name: Docker Scout Analysis
        run: |
          # Substitua "my-image:tag" pela sua imagem Docker
          docker scout quickview my-image:tag
